Compensation(Dummy for test) and Withdraw Compensation
xwinfinance/xWinBSC pull request #1
Opened 2022-05-21 23:41 UTC by Takunari

I pushed the "Withdraw Compensation contract". PLS take a look at the sources. Thanks

2022-05-26 05:40 UTC, Jolly-Walker requested changes

2022-05-26 05:40 UTC, Jolly-Walker commented on src/contract-v2/xWinRobustCompensation.sol
> +    address public targetToken = address(0xd88ca08d8eec1E9E09562213Ae83A7853ebB5d28);
uncomment this line, use mainnet token

2022-05-26 05:40 UTC, Jolly-Walker commented on src/contract-v2/xWinRobustCompensation.sol
> +        hasWithdrawed[msg.sender] = true;
move this line of code 754 to before the transfer call at line 743

2022-05-26 12:54 UTC, Josezawa commented on src/contract-v2/xWinRobustCompensation.sol
> +    address public targetToken = address(0xd88ca08d8eec1E9E09562213Ae83A7853ebB5d28);
Ok,
should I change the address of the xWinCompensation?
`   xWinCompensation _xWinCompensation = xWinCompensation(address(0xB722B10c219442501f60d014FCD41A9C7fe65B75));`
currently I'm using address of the xWinCompensation on the test net.

2022-05-26 13:10 UTC, Josezawa commented on src/contract-v2/xWinRobustCompensation.sol
> +        hasWithdrawed[msg.sender] = true;
OK,
I wondered whether the user could withdraw or could not withdraw anymore if the status changed before the transfer and the transfer failed.

2022-05-26 13:29 UTC, Josezawa commented
[Jolly-Walker](https://github.com/Jolly-Walker),  PLS  review the following changes. Thanks
[1a23eb7](https://github.com/xwinfinance/xWinBSC/pull/1/commits/1a23eb7061099728a3624d2b4224ec6a86a81fd0)

2022-05-27 06:28 UTC, xwinfinance approved these changes

2022-05-27 06:29 UTC, merged